Repository JRaviLab/MolEvolvR, pull requests merged in 2024-10, with the labels that each got.

#65 Rename functions in acc2lin
  NAMESPACE
  R/acc2lin.R
  R/lineage.R
  man/IPG2Lineage.Rd
  man/acc2Lineage.Rd
  man/addlineage.Rd
  man/efetchIPG.Rd
  man/sinkReset.Rd
Labels: bug, enhancement

#66 Refactored function names in R/tree.R
  NAMESPACE
  R/tree.R
  man/convertAlignment2Trees.Rd
  man/convertFA2Tree.Rd
  man/createFA2Tree.Rd
Labels: bug

#68 Refactored function names in R/plotme.R
  NAMESPACE
  R/plotme.R
  man/create_all_col_params.Rd
  man/create_one_col_params.Rd
  man/plotSunburst.Rd
  man/prepareColumnParams.Rd
  man/prepareSingleColumnParams.Rd
  man/validateCountDF.Rd
Labels: bug

#69 Refactored function names in R/lineage.R
  NAMESPACE
  R/acc2lin.R
  R/lineage.R
  man/GCA2Lineage.Rd
  man/IPG2Lineage.Rd
  man/acc2Lineage.Rd
  man/addLineage.Rd
  man/addTaxID.Rd
  man/downloadAssemblySummary.Rd
  man/prot2tax.Rd
  man/proteinAcc2TaxID.Rd
  man/proteinAcc2TaxID_old.Rd
Labels: bug

#81 Refactored function names in R/job_status_emails.R
  NAMESPACE
  R/job_status_emails.R
  man/createJobResultsURL.Rd
  man/createJobStatusEmailMessage.Rd
  man/formatJobArgumentsHTML.Rd
  man/sendJobStatusEmail.Rd
Labels: bug

#39 Add parameter definitions to acc2lin.R
  R/acc2lin.R
  man/IPG2Lineage.Rd
  man/acc2Lineage.Rd
  man/addLineage.Rd
  man/efetchIPG.Rd
Labels: documentation

#40 Add parameter definitions to tree.R
  R/tree.R
  man/convertAlignment2Trees.Rd
  man/convertFA2Tree.Rd
  man/createFA2Tree.Rd
Labels: documentation

#41 Add parameter definitions to summarize.R
  R/summarize.R
  man/MolEvolvR_summary.Rd
  man/countbycolumn.Rd
  man/elements2Words.Rd
  man/filterbydomains.Rd
  man/filterbyfrequency.Rd
  man/findparalogs.Rd
  man/summarizeDomArch.Rd
  man/summarizeDomArch_ByLineage.Rd
  man/summarizeGenContext.Rd
  man/summarizeGenContext_ByDomArchLineage.Rd
  man/summarizeGenContext_ByLineage.Rd
  man/summarizebylineage.Rd
  man/totalgencontextordomarchcounts.Rd
  man/words2wordcounts.Rd
Labels: documentation

#56 Improve CONTRIBUTING.md with clear installation instructions and detailed development process
  .github/.gitignore
  .github/CONTRIBUTING.md
Labels: documentation

#83 Refactored function names in R/ipr2viz.R
  NAMESPACE
  R/ipr2viz.R
  man/countByColumn.Rd
  man/filterByDomains.Rd
  man/filterByFrequency.Rd
  man/findParalogs.Rd
  man/getTopAccByLinDomArch.Rd
  man/plotIPR2Viz.Rd
  man/plotIPR2VizWeb.Rd
  man/themeGenes2.Rd
  man/words2WordCounts.Rd
Labels: bug

#87 refactor function names in R/pre-msa-tree and R/reverse-operons.R
  NAMESPACE
  R/CHANGED-pre-msa-tree.R
  R/pre-msa-tree.R
  R/reverse_operons.R
  man/acc2fa.Rd
  man/addLeaves2Alignment.Rd
  man/addName.Rd
  man/add_leaves.Rd
  man/add_name.Rd
  man/alignFasta.Rd
  man/convert2TitleCase.Rd
  man/convertAlignment2FA.Rd
  man/convert_aln2fa.Rd
  man/createRepresentativeAccNum.Rd
  man/generateAllAlignments2FA.Rd
  man/generate_all_aln2fa.Rd
  man/getAccNumFromFA.Rd
  man/get_accnums_from_fasta_file.Rd
  man/mapAcc2Name.Rd
  man/map_acc2name.Rd
  man/reverseOperonSeq.Rd
  man/straightenOperonSeq.Rd
  man/to_titlecase.Rd
  man/writeMSA_AA2FA.Rd
Labels: bug

#42 Implement error handling in acc2lin.R functions
  R/acc2lin.R
  man/acc2lin.Rd
  man/efetch_ipg.Rd
  man/ipg2lin.Rd
  man/sink.reset.Rd
Labels: outreachy

#99 Refactor function names in R/blastWrapper.R
  NAMESPACE
  R/blastWrappers.R
  man/runDeltaBlast.Rd
  man/runRPSBlast.Rd
Labels: documentation, outreachy

#101 Refactored function names in msa.R | networks_domarch.R | networks_gencontext.R
  NAMESPACE
  R/msa.R
  R/networks_domarch.R
  R/networks_gencontext.R
  man/createBinaryDomainNetwork.Rd
  man/createDomainNetwork.Rd
  man/createGenomicContextNetwork.Rd
  man/createMSA_Kalign.Rd
  man/createMSA_PDF.Rd
  man/createUndirectedGenomicContextNetwork.Rd
Labels: documentation, outreachy

#85 Refactor: Externalize .LevelReduction and .GetKingdom for global use
  .gitignore
  R/plotting.R
Labels: outreachy

#76 Added error handling to multiple functions in R/assign_job_queue.R, R/blastWrappers.R
  NAMESPACE
  R/acc2lin.R
  R/assign_job_queue.R
  R/blastWrappers.R
Labels: enhancement, outreachy

#70 add error handling in tree.R
  R/tree.R
Labels: outreachy

#72 add error handling in reverse_operons
  R/reverse_operons.R
Labels: outreachy

#74 add input checks in pre-msa-tree
  R/pre-msa-tree.R
Labels: outreachy
